server:
  port: 6781


eureka:
  instance:
    hostname: node1
  client:
    registerWithEureka: false
    fetchRegistry: false
spring:
  application:
    name: eureka-server


#eureka:
#  instance:
#    hostname: node1
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://node2:6782/eureka/,http://node3:6783/eureka/
#spring:
#  application:
#    name: eureka-server
