spring:
  application:
    name: eureka-client3

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6781/eureka
#      defaultZone: http://localhost:6781/eureka,http://localhost:6782/eureka,http://localhost:6783/eureka

server:
  port: 8764
