spring:
  application:
    name: eureka-client1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6781/eureka,http://localhost:6782/eureka,http://localhost:6783/eureka

server:
  port: 8082
